name: paper_app
description: A sample web application
dependencies:
  browser: any
  core_elements: '>=0.1.0 <0.2.0'
  paper_elements: '0.1.0+2 < 0.2.0'
  polymer: '>=0.12.0 <0.13.0'
environment:
  sdk: ">=1.0.0 <2.0.0"
  
transformers:
- polymer:
    entry_points: web/index.html